language: ruby
rvm:
  - 2.2.2
before_script:
  cp spec/dummy/config/database.travis.yml spec/dummy/config/database.yml

script:
  - cd spec/dummy
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - cd ../..
  - bundle exec rake
